### ISSUE TITLE
Support for Erlang/OTP 22?

### ISSUE THREAD

**Issue by dcaixinha** [elitau/pact_elixir#95]
Hey,

First of all thank you for the library :raised_hands: I'm using it for the first time in a project that's running Erlang/OTP 22, and I'm getting the following error:
```
==> pact_elixir
Compiling NIF crate :pactmockserver (native/pactmockserver)...
   Compiling erlang_nif-sys v0.6.4
   Compiling url v1.5.1
   Compiling unicase v1.4.2
   Compiling rustler_codegen v0.18.0
   Compiling env_logger v0.4.3
error: failed to run custom build command for `erlang_nif-sys v0.6.4`

Caused by:
  process didn't exit successfully: `/home/app/elixir-artifacts/_build/service_level_test/rustler_crates/pac
tmockserver/release/build/erlang_nif-sys-530dba2e3c1f88c9/build-script-build` (exit code: 101)
--- stdout
Unsupported Erlang version.

Is the erlang_nif-sys version up to date in the Cargo.toml?
Does 'cargo update' fix it?
If not please report at https://github.com/goertzenator/erlang_nif-sys.

--- stderr
thread 'main' panicked at 'gen_api.erl encountered an error.', /home/app/.cargo/registry/src/github.com-1ecc
6299db9ec823/erlang_nif-sys-0.6.4/build.rs:28:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Is it possible to add support for Erlang/OTP 22? Is it just a matter of updating the `rustler` version in the `Cargo.toml`? If so, I don't mind submitting a PR! Thanks in advance :bowing_man:

**Comment by elitau** [comment]
Hey,

I've updated the library to support Erlang/OTP 22 in [version 0.5.2](https://hex.pm/packages/pact_elixir/0.5.2).

Please try it out.

**Comment by dcaixinha** [comment]
Hey @elitau, thanks for the timely response :raised_hands: 

Just tested this now and everything works :white_check_mark: Closing the issue!
